import { RawArticle } from './pipeline'

export const seedArticles: RawArticle[] = [
  {
    title: "Zomato's Blinkit Crosses $1 Billion ARR as Quick Commerce Boom Continues",
    url: "https://example.com/zomato-blinkit-1b-arr",
    summary: "Zomato's quick commerce arm Blinkit has crossed the $1 billion annual revenue run rate, making it one of the fastest-growing segments in Indian e-commerce. The company plans to expand dark stores to 1,000 by FY26.",
    full_text: "Zomato's quick commerce arm Blinkit has crossed the $1 billion annual revenue run rate (ARR), marking a major milestone for the Deepinder Goyal-led company. Blinkit, which delivers groceries and essentials in under 10 minutes, has seen revenue grow 120% year-over-year. The company currently operates over 600 dark stores across 30 cities and plans to expand to 1,000 dark stores by the end of FY26. Analysts at Goldman Sachs have raised Zomato's target price to ₹320, citing the exponential growth in quick commerce. The segment now contributes nearly 40% of Zomato's overall gross order value.",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
    published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Paytm Gets RBI Nod to Resume Onboarding New Customers on Paytm Payments Bank",
    url: "https://example.com/paytm-rbi-nod",
    summary: "In a major relief for One97 Communications, the RBI has conditionally allowed Paytm Payments Bank to resume onboarding new customers after a six-month ban. The stock surged 12% on the news.",
    full_text: "The Reserve Bank of India has given conditional approval to Paytm Payments Bank to resume onboarding new customers, ending a six-month regulatory freeze. The RBI had barred PPBL from adding customers in January 2024 citing compliance concerns. Paytm must comply with strict KYC norms and data localization requirements. CEO Vijay Shekhar Sharma called it a 'new chapter' for the company. Shares of One97 Communications surged 12% to ₹485 on the BSE following the announcement. Analysts expect the company to regain market share in the digital payments space over the next two quarters.",
    image_url: "https://images.unsplash.com/photo-1556742111-a301076d9d18?w=800",
    published_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Swiggy IPO: Company Files DRHP with SEBI for ₹10,000 Crore Public Offering",
    url: "https://example.com/swiggy-ipo-drhp",
    summary: "Swiggy has filed its Draft Red Herring Prospectus with SEBI for a ₹10,000 crore IPO. The offering includes a fresh issue of ₹3,750 crore and an OFS of ₹6,250 crore from existing investors including SoftBank and Prosus.",
    full_text: "Food and grocery delivery platform Swiggy has filed its Draft Red Herring Prospectus (DRHP) with the Securities and Exchange Board of India for a ₹10,000 crore initial public offering. The IPO comprises a fresh issue of shares worth ₹3,750 crore, while existing shareholders including SoftBank, Prosus, and Accel will sell shares worth ₹6,250 crore. Swiggy reported revenue of ₹8,265 crore in FY24, up 36% from the previous year. The company's Instamart quick commerce business has been growing at 50% QoQ. Swiggy is expected to be listed at a valuation of $15 billion.",
    image_url: "https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800",
    published_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Zepto Raises $665 Million at $3.6 Billion Valuation, Plans Profitability by Q4 FY25",
    url: "https://example.com/zepto-fundraise-665m",
    summary: "Quick commerce startup Zepto has raised $665 million in a fresh funding round led by StepStone Group and Goodwater Capital. The company claims profitability in 6 of its top 8 cities.",
    full_text: "Quick commerce platform Zepto has raised $665 million in its latest funding round, valuing the Aadit Palicha-led startup at $3.6 billion. The round was led by StepStone Group, Goodwater Capital, and existing investors including Glade Brook Capital and Nexus Venture Partners. Zepto, which delivers groceries in 10 minutes, claims to be profitable in six of its top eight cities and targets company-wide profitability by Q4 FY25. The company operates over 350 dark stores and processes over 5 million orders daily. The fresh capital will be used for expansion into tier-2 cities and investments in supply chain technology.",
    image_url: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800",
    published_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Reliance Jio Financial Services Gets RBI Approval for NBFC License",
    url: "https://example.com/reliance-jio-fin-nbfc",
    summary: "Reliance Jio Financial Services has received RBI approval for its NBFC license, paving the way for the Ambani-owned entity to offer digital lending, insurance, and mutual fund products.",
    full_text: "Reliance Jio Financial Services (RJFS) has received the Reserve Bank of India's approval for its Non-Banking Financial Company license. This regulatory clearance enables RJFS to launch digital lending products, insurance distribution, and mutual fund offerings through its digital platform. The company, which was demerged from Reliance Industries in August 2023, plans to leverage Jio's 450 million telecom subscriber base. Analysts at JP Morgan estimate the lending opportunity at ₹50,000 crore within three years. RJFS shares closed 5.2% higher at ₹312 on the NSE.",
    image_url: "https://images.unsplash.com/photo-1559526324-593bc073d938?w=800",
    published_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "HDFC Bank Reports 22% Growth in Q3 Net Profit, Asset Quality Stable",
    url: "https://example.com/hdfc-bank-q3-results",
    summary: "HDFC Bank reported a 22% year-on-year increase in Q3 net profit to ₹16,735 crore. Net interest margin held steady at 3.4%, beating analyst estimates of 3.3%.",
    full_text: "HDFC Bank, India's largest private-sector lender, reported a 22% year-on-year increase in net profit for Q3 FY25 to ₹16,735 crore, beating analyst estimates of ₹15,800 crore. Net interest income grew 8.5% to ₹30,650 crore. The bank's net interest margin (NIM) held steady at 3.4%, higher than the consensus estimate of 3.3%. Gross non-performing assets (NPA) remained stable at 1.24%. The bank added 1.1 million new credit card customers during the quarter. HDFC Bank's total deposits crossed ₹24 lakh crore post the merger with HDFC Ltd. The stock gained 3.1% in early trading following the results.",
    image_url: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=800",
    published_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Infosys Wins $2 Billion Mega Deal from European Telecom Giant",
    url: "https://example.com/infosys-2b-deal",
    summary: "Infosys has bagged a $2 billion multi-year deal from a leading European telecom operator for cloud transformation and AI-driven customer experience management.",
    full_text: "IT major Infosys has won a $2 billion deal from a leading European telecommunications operator, one of the largest deals in the Indian IT sector this year. The multi-year engagement covers cloud infrastructure modernization, AI-driven customer experience platforms, and 5G network automation. CEO Salil Parekh described the deal as 'transformational' for Infosys's telecom vertical. The company has been investing heavily in generative AI capabilities and recently launched its Topaz AI platform. Total contract value (TCV) for Q3 stood at $4.1 billion, up 28% year-on-year. Infosys raised its FY25 revenue growth guidance to 4-5% from the earlier 3-4%.",
    image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800",
    published_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Ola Electric IPO Day 1: Stock Lists at 20% Premium, Market Cap Touches ₹40,000 Crore",
    url: "https://example.com/ola-electric-ipo-listing",
    summary: "Ola Electric shares listed at a 20% premium to the IPO price of ₹76, opening at ₹91.2 on the BSE. The company's market capitalization touched ₹40,000 crore on listing day.",
    full_text: "Ola Electric Mobility shares made a strong debut on the stock exchanges, listing at a 20% premium to the IPO price of ₹76. The stock opened at ₹91.2 on the BSE and touched an intraday high of ₹98.5, giving the company a market capitalization of approximately ₹40,000 crore. The IPO was subscribed 4.4 times, with the retail portion subscribed 3.5 times. CEO Bhavish Aggarwal said the listing 'validates India's EV revolution.' Ola Electric holds a 35% market share in India's electric two-wheeler segment. Analysts at Morgan Stanley have initiated coverage with an 'overweight' rating and a target price of ₹120.",
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800",
    published_at: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Byju's Faces Insolvency as NCLT Admits Case Filed by BCCI",
    url: "https://example.com/byjus-insolvency-nclt",
    summary: "The NCLT has admitted an insolvency petition against Think & Learn (Byju's) filed by BCCI over unpaid sponsorship dues of ₹158 crore. The edtech giant's valuation has eroded from $22B to near zero.",
    full_text: "The National Company Law Tribunal (NCLT) has admitted an insolvency petition against Think & Learn Private Limited, the parent company of edtech platform Byju's. The petition was filed by the Board of Control for Cricket in India (BCCI) over unpaid sponsorship dues of ₹158 crore. This marks a dramatic fall for the company that was once India's most valuable startup at $22 billion. Byju's has faced a series of setbacks including investor lawsuits, mass layoffs, and a $533 million rights issue dispute with its own shareholders. Former Deloitte partner Pankaj Srivastava has been appointed as the Interim Resolution Professional (IRP).",
    image_url: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800",
    published_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "SEBI Tightens F&O Rules: Lot Sizes Doubled, Weekly Expiry Limited to One Exchange",
    url: "https://example.com/sebi-fno-rules",
    summary: "SEBI has announced sweeping changes to derivatives trading rules, doubling minimum lot sizes and restricting weekly expiry to one exchange per index, effective from April 1.",
    full_text: "The Securities and Exchange Board of India has announced significant changes to futures and options (F&O) trading regulations aimed at curbing speculative retail trading. Key changes include: doubling the minimum lot size for index derivatives from ₹5 lakh to ₹10 lakh, restricting weekly expiry contracts to one exchange per index, increasing margin requirements for short options by 2%, and mandating a cooling-off period for intraday positions. SEBI Chairperson Madhabi Puri Buch said 9 out of 10 retail F&O traders lose money. The changes will be effective from April 1. NSE and BSE indices fell 1.5% following the announcement.",
    image_url: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800",
    published_at: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "RBI Keeps Repo Rate Unchanged at 6.5%, Signals Possible Cut in February",
    url: "https://example.com/rbi-repo-rate-hold",
    summary: "The RBI's Monetary Policy Committee held the repo rate at 6.5% for the 10th consecutive time but changed its stance to 'neutral', signaling a potential rate cut in the February 2025 meeting.",
    full_text: "The Reserve Bank of India's Monetary Policy Committee (MPC) has kept the benchmark repo rate unchanged at 6.5% for the 10th consecutive time. However, in a significant shift, the MPC changed its monetary policy stance from 'withdrawal of accommodation' to 'neutral', with a 5-1 vote. RBI Governor Shaktikanta Das said inflation remains elevated but is moving towards the 4% target. GDP growth forecast for FY25 was retained at 7.2%. Bond yields fell 5 basis points to 6.72% following the announcement. Markets are now pricing in a 25 bps rate cut at the February 2025 meeting.",
    image_url: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800",
    published_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "PhonePe Completes $350M Secondary Round, Valuation Steady at $12 Billion",
    url: "https://example.com/phonepe-secondary-round",
    summary: "PhonePe has completed a $350 million secondary share sale at a $12 billion valuation. Early employees and angel investors cashed out as the Walmart-backed company prepares for an IPO.",
    full_text: "Digital payments giant PhonePe has completed a $350 million secondary share sale at a steady $12 billion valuation. The transaction allowed early employees, angel investors, and some early-stage institutional investors to cash out their holdings. General Atlantic, Tiger Global, and Ribbit Capital participated as buyers in the secondary sale. PhonePe processes over 5 billion UPI transactions monthly, accounting for a 48% market share. The company turned operationally profitable in FY24 and is expected to file for an IPO in 2025-26. CEO Sameer Nigam said the company is exploring financial services expansion across insurance, lending, and investments.",
    image_url: "https://images.unsplash.com/photo-1556742400-b5b7c512f3b0?w=800",
    published_at: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Tata Motors EV Sales Surge 65% in Q3, Nexon EV Dominates Market with 62% Share",
    url: "https://example.com/tata-motors-ev-q3",
    summary: "Tata Motors reported a 65% surge in electric vehicle sales in Q3, with the Nexon EV maintaining a dominant 62% share of India's electric passenger vehicle market.",
    full_text: "Tata Motors has reported a 65% year-on-year surge in electric vehicle sales during Q3 FY25, selling 18,500 units compared to 11,200 units in the same period last year. The Nexon EV continues to dominate India's electric passenger vehicle market with a 62% share. The Tiago EV, priced from ₹7.99 lakh, has expanded the EV market to first-time car buyers. Tata Motors has announced plans to launch 10 new EV models by 2027 under its Avinya and Curvv platforms. The company's JLR subsidiary also saw strong results with Land Rover Defender sales up 32% globally.",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800",
    published_at: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Razorpay Turns Profitable, Eyes IPO in 2025 at $8 Billion Valuation",
    url: "https://example.com/razorpay-profitable-ipo",
    summary: "Fintech unicorn Razorpay has turned profitable for the first time, reporting a net profit of ₹33 crore in FY24. The company is planning an IPO at an $8 billion valuation.",
    full_text: "Payment gateway and financial services platform Razorpay has reported its first-ever annual profit, posting a net income of ₹33 crore for FY24 on revenue of ₹2,501 crore. The company processed $180 billion in total payment volume during the year, a 45% increase from FY23. Co-founder Harshil Mathur confirmed that Razorpay is exploring an IPO in 2025 at an expected valuation of $8 billion. The company has expanded beyond payments into business banking, payroll, and lending. Razorpay serves over 10 million businesses and recently received an in-principle approval for a payment aggregator license from the RBI.",
    image_url: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800",
    published_at: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Adani Group to Invest ₹1.2 Lakh Crore in Green Hydrogen, Plans World's Largest Plant",
    url: "https://example.com/adani-green-hydrogen",
    summary: "Adani New Industries Limited plans to invest ₹1.2 lakh crore in green hydrogen production, including the world's largest green hydrogen plant in Gujarat's Kutch district.",
    full_text: "Adani New Industries Limited (ANIL), a subsidiary of Adani Group, has announced plans to invest ₹1.2 lakh crore ($15 billion) in green hydrogen production over the next decade. The centerpiece is the world's largest green hydrogen plant in Khavda, Gujarat's Kutch district, with a planned capacity of 1 million tonnes per annum. The project will be powered by 30 GW of solar and wind energy. Adani Green Energy CEO Vneet Jaain said the plant will produce green hydrogen at under $2 per kg by 2030, making it cost-competitive with grey hydrogen. The announcement comes as India targets 5 million tonnes of green hydrogen production by 2030 under the National Green Hydrogen Mission.",
    image_url: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800",
    published_at: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Meesho Achieves First Full-Year Profitability, Revenue Crosses ₹6,000 Crore",
    url: "https://example.com/meesho-profitable",
    summary: "Social commerce platform Meesho reported its first full year of profitability with a net profit of ₹115 crore in FY24, driven by cost optimization and a 40% revenue growth.",
    full_text: "Social commerce platform Meesho has reported its first full year of profitability, posting a net profit of ₹115 crore in FY24 on revenue of ₹6,120 crore. This represents a 40% year-on-year revenue growth while overall costs decreased by 12%. CEO Vidit Aatrey attributed the turnaround to focus on unit economics and supply chain optimization. Meesho serves 160 million transacting users across India, primarily from tier-2 and tier-3 cities. The company has decided to delay its IPO plans to FY26 to demonstrate sustained profitability. Meesho's marketplace model has attracted over 1.5 million sellers.",
    image_url: "https://images.unsplash.com/photo-1556742077-0a6b6a4a4ac4?w=800",
    published_at: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "ICICI Bank Launches AI-Powered Wealth Management Platform for HNI Customers",
    url: "https://example.com/icici-ai-wealth",
    summary: "ICICI Bank has launched an AI-powered wealth management platform using generative AI to provide personalized investment recommendations for its 2.5 lakh HNI customers.",
    full_text: "ICICI Bank has launched 'iWealth AI', an artificial intelligence-powered wealth management platform for its high-net-worth individual (HNI) customers. The platform uses generative AI models to analyze market conditions, portfolio risk, and individual investor preferences to generate personalized investment recommendations. Available to customers with portfolios above ₹1 crore, the platform offers automated portfolio rebalancing, tax-loss harvesting suggestions, and real-time market alerts. ICICI Bank has invested over ₹500 crore in AI and machine learning capabilities over the past two years. The bank's wealth management AUM stands at ₹5.2 lakh crore.",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
    published_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Dream11's Parent Dream Sports Achieves ₹1,000 Crore Profit, Becomes India's Most Profitable Gaming Company",
    url: "https://example.com/dream11-profit-1000cr",
    summary: "Dream Sports, parent of fantasy sports platform Dream11, reported a net profit of ₹1,000 crore in FY24, making it India's most profitable gaming company.",
    full_text: "Dream Sports, the parent company of fantasy sports platform Dream11, has reported a net profit of ₹1,000 crore for FY24 on revenue of ₹5,870 crore. This makes Dream Sports India's most profitable online gaming company. The platform has 220 million registered users and saw 25% growth in paid users. CEO Harsh Jain said the company has benefited from regulatory clarity following the GST Council's decision to levy 28% GST on the entry amount. Dream Sports has also launched Dream Pay, a payments vertical, and FanCode, a sports content platform. The company is in preliminary discussions for an IPO at a $12 billion valuation.",
    image_url: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800",
    published_at: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Bharti Airtel's 5G User Base Crosses 100 Million, ARPU Rises to ₹211",
    url: "https://example.com/airtel-5g-100m",
    summary: "Bharti Airtel's 5G subscriber base has crossed 100 million within 18 months of launch. Average revenue per user (ARPU) rose to an all-time high of ₹211.",
    full_text: "Bharti Airtel has announced that its 5G subscriber base has crossed the 100 million mark, just 18 months after launching 5G services in India. The company's average revenue per user (ARPU) rose to an all-time high of ₹211, up from ₹200 in the previous quarter. Airtel's 5G network now covers all major cities and 80% of tier-2 towns. CEO Gopal Vittal said 5G is driving increased data consumption and premium plan adoption. The company reported a consolidated net profit of ₹4,160 crore for Q3 FY25, up 34% year-on-year. Airtel's enterprise segment, Airtel Business, grew revenues by 18% to ₹5,400 crore.",
    image_url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800",
    published_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Nykaa's Fashion Segment Turns EBITDA Positive for First Time",
    url: "https://example.com/nykaa-fashion-ebitda",
    summary: "FSN E-Commerce (Nykaa) announced that its fashion segment has turned EBITDA positive for the first time, with the beauty segment maintaining 8% EBITDA margins.",
    full_text: "FSN E-Commerce Ventures (Nykaa) has announced that its fashion segment, Nykaa Fashion, has achieved EBITDA profitability for the first time. The segment reported an EBITDA margin of 1.2% in Q3 FY25, up from -4.5% in the same quarter last year. The beauty vertical maintained its healthy 8% EBITDA margin. Overall, Nykaa reported consolidated revenue of ₹1,890 crore for Q3, up 23% year-on-year, with a net profit of ₹28 crore. Founder Falguni Nayar said the company is focusing on private label brands, which now contribute 15% of beauty revenue. Nykaa has opened 180 physical stores across 65 cities.",
    image_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800",
    published_at: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Flipkart Launches AI Shopping Assistant 'Flippi 2.0' with Visual Search and Voice Commands",
    url: "https://example.com/flipkart-flippi-ai",
    summary: "Flipkart has launched Flippi 2.0, an AI-powered shopping assistant that can understand visual queries, voice commands, and contextual searches in 8 Indian languages.",
    full_text: "Walmart-owned Flipkart has launched Flippi 2.0, a next-generation AI shopping assistant powered by its custom large language model. The assistant supports visual search (users can upload images to find similar products), voice commands in 8 Indian languages, and contextual search that understands intent. In beta testing, Flippi 2.0 improved product discovery by 45% and increased conversion rates by 12%. Flipkart CTO Ravi Garikipati said the company has deployed AI across its supply chain, resulting in a 20% reduction in delivery times. The launch positions Flipkart to compete with Amazon India's Rufus AI assistant.",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
    published_at: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "L&T Reports Record Order Book of ₹4.8 Lakh Crore, Infrastructure Pipeline Strong",
    url: "https://example.com/lt-record-order-book",
    summary: "Larsen & Toubro reported a record order book of ₹4.8 lakh crore, driven by strong momentum in infrastructure, defence, and green energy projects.",
    full_text: "Engineering conglomerate Larsen & Toubro has reported a record order book of ₹4.8 lakh crore for Q3 FY25, up 19% year-on-year. The company won new orders worth ₹76,000 crore during the quarter, with significant wins in defence (₹18,000 crore), green hydrogen infrastructure (₹12,000 crore), and urban metro rail projects (₹15,000 crore). L&T's IT subsidiary LTIMindtree also reported strong results with 5.2% revenue growth. Chairman SN Subrahmanyan said the company's execution capabilities are at 'peak performance' with 85% on-time project delivery. L&T has raised its FY25 order inflow guidance by 10%.",
    image_url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800",
    published_at: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Startup Funding Rebounds: Indian Startups Raise $3.2 Billion in Q3 2024",
    url: "https://example.com/startup-funding-q3-2024",
    summary: "Indian startups raised $3.2 billion across 280 deals in Q3 2024, a 42% increase from Q2, signaling a recovery in the venture capital ecosystem after the 2023 downturn.",
    full_text: "Indian startups raised $3.2 billion in funding across 280 deals in Q3 2024, marking a 42% increase from Q2 2024's $2.25 billion and signaling a recovery in the venture capital ecosystem. The top sectors by funding were fintech ($780 million), deeptech/AI ($540 million), SaaS ($420 million), and healthtech ($310 million). Notable rounds included Zepto's $665 million raise and Lenskart's $200 million round at $5 billion valuation. Late-stage funding showed the strongest recovery, up 68% QoQ. However, seed-stage funding remains sluggish. Accel, Peak XV Partners, and Lightspeed were the most active investors.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800",
    published_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Wipro's AI Revenue Crosses $1 Billion, Beats Industry Growth Rate",
    url: "https://example.com/wipro-ai-revenue-1b",
    summary: "Wipro's AI and cloud-related services revenue has crossed the $1 billion annual run rate. CEO Thierry Delaporte highlighted 'ai360' as the growth engine for the coming quarters.",
    full_text: "IT services company Wipro has announced that its AI and cloud-related services revenue has crossed the $1 billion annual run rate, growing at 35% year-on-year. Wipro's 'ai360' initiative, launched last year, has been adopted by over 200 enterprise clients. The company has deployed AI copilots across software development, testing, and customer service operations, resulting in 30-40% productivity improvements for clients. CEO Thierry Delaporte said AI is 'no longer a nice-to-have' and expects AI-related revenue to reach $2 billion by FY27. Wipro also announced a $150 million investment in its Bengaluru AI research lab.",
    image_url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800",
    published_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "UPI Transaction Volume Hits Record 14.7 Billion in October 2024",
    url: "https://example.com/upi-record-oct-2024",
    summary: "UPI transactions hit an all-time high of 14.7 billion in October 2024, processing ₹20.4 lakh crore in value. NPCI is now expanding UPI to 20 countries.",
    full_text: "The Unified Payments Interface (UPI) recorded an all-time high of 14.7 billion transactions in October 2024, processing a total value of ₹20.4 lakh crore ($245 billion). This represents a 48% year-on-year growth in volume and 38% growth in value. Person-to-merchant transactions now account for 55% of total volume, up from 42% a year ago. NPCI International has signed agreements to enable UPI in 20 countries, including Japan, South Korea, and Kenya. UPI credit linked to RuPay credit cards processed transactions worth ₹2,400 crore, a 12x increase from the previous year. PhonePe leads with 48% share, followed by Google Pay at 36% and Paytm at 8%.",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
    published_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "CRED's Valuation Rises to $10 Billion After New Strategic Round from GIC, Tiger Global",
    url: "https://example.com/cred-10b-valuation",
    summary: "Fintech platform CRED has raised $200 million from Singapore's GIC and Tiger Global, valuing the Kunal Shah-founded company at $10 billion.",
    full_text: "Fintech platform CRED, founded by Kunal Shah, has raised $200 million in a strategic round from Singapore's sovereign wealth fund GIC and Tiger Global Management. The round values CRED at $10 billion, up from $6.4 billion in its last round. CRED, which started as a credit card bill payment app, has expanded into rentals, travel, and commerce. The platform now has 15 million users with an average credit score of 830. CRED's commerce vertical, CRED Store, has grown 300% year-on-year. The company claims to be on track for profitability by FY26. Revenue for FY24 stood at ₹2,400 crore, up 65% year-on-year.",
    image_url: "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=800",
    published_at: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Sensex Crosses 80,000 for First Time, Led by Banking and IT Stocks",
    url: "https://example.com/sensex-80000",
    summary: "The BSE Sensex crossed the 80,000 mark for the first time, driven by strong FII inflows, banking sector rally, and global risk appetite. India is now the world's 4th largest stock market.",
    full_text: "The BSE Sensex has breached the 80,000 mark for the first time in history, closing at 80,234 points. The milestone was driven by strong foreign institutional investor (FII) inflows of ₹28,000 crore in the last month, a rally in banking stocks following HDFC Bank and ICICI Bank's strong results, and renewed global risk appetite. India's total stock market capitalization now stands at $4.8 trillion, making it the world's 4th largest stock market after the US, China, and Japan. The Nifty 50 closed above 24,300. Market breadth was positive with 35 of the 50 Nifty stocks closing in the green. Analysts expect the rally to continue as India's GDP growth remains robust at 7.2%.",
    image_url: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800",
    published_at: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "JSW Group Enters Semiconductor Manufacturing with ₹15,000 Crore Gujarat Fab",
    url: "https://example.com/jsw-semiconductor-fab",
    summary: "JSW Group has announced a ₹15,000 crore semiconductor fabrication plant in Gujarat's Dholera SIR, partnering with Israel's Tower Semiconductor for technology transfer.",
    full_text: "JSW Group has announced a ₹15,000 crore ($1.8 billion) investment in a semiconductor fabrication plant at the Dholera Special Investment Region (SIR) in Gujarat. The plant, developed in partnership with Israel's Tower Semiconductor, will manufacture 65nm and 45nm chips primarily for automotive and industrial applications. The fab is expected to produce 40,000 wafer starts per month by 2028. JSW Group Chairman Sajjan Jindal said the project aligns with India's Semiconductor Mission and will create 3,000 direct jobs. The Government of India will provide 50% of the capital expenditure as incentive under the Modified Semiconductor Programme. This is the third semiconductor fab approved by the government.",
    image_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
    published_at: new Date(Date.now() - 29 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "Mamaearth Parent Honasa Consumer Reports First Profitable Quarter Post-IPO",
    url: "https://example.com/honasa-profitable-quarter",
    summary: "Honasa Consumer, parent of Mamaearth and BBlunt, reported its first quarterly net profit of ₹30 crore post-IPO. Revenue grew 28% to ₹560 crore in Q3 FY25.",
    full_text: "Honasa Consumer, the parent company of D2C beauty brands Mamaearth and BBlunt, has reported its first quarterly net profit post-IPO, posting a net income of ₹30 crore in Q3 FY25 compared to a loss of ₹18 crore in the same quarter last year. Revenue grew 28% year-on-year to ₹560 crore. The Mamaearth brand contributed ₹420 crore in revenue, while The Derma Co. grew 55% to reach ₹95 crore. Founder Varun Alagh said the company is focusing on offline expansion, with products now available in 1.5 lakh retail outlets across India. EBITDA margins improved to 7.2% from 1.8% a year ago.",
    image_url: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800",
    published_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    title: "India's SaaS Industry Revenue Hits $16 Billion, 4 New Unicorns in 2024",
    url: "https://example.com/india-saas-16b",
    summary: "India's SaaS industry revenue has hit $16 billion with 4 new unicorns in 2024 — Darwinbox, CleverTap, Amagi, and Rocketlane. The industry is on track for $50 billion by 2030.",
    full_text: "India's Software-as-a-Service (SaaS) industry revenue has reached $16 billion in 2024, according to a report by SaaSBoomi and McKinsey. Four new SaaS unicorns emerged in 2024: Darwinbox (HR tech), CleverTap (customer engagement), Amagi (media tech), and Rocketlane (professional services automation). The report projects India's SaaS revenue will reach $50 billion by 2030, driven by AI-native products and vertical SaaS solutions. India now has 32 SaaS unicorns and over 25,000 SaaS startups. Freshworks, Zoho, and Zenoti remain the largest Indian SaaS companies by revenue. GenAI adoption among Indian SaaS companies has reached 60%, the highest in the world.",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800",
    published_at: new Date(Date.now() - 31 * 60 * 60 * 1000).toISOString(),
  },
]
